Repository elastic/elasticsearch-rs, pull requests merged in 2020-01, with the labels that each got.

#49 Make ConnectionPool Sync/Send
  elasticsearch/src/http/transport.rs
Labels: enhancement

#50 Connection url ends in trailing forward slash
  elasticsearch/src/http/transport.rs
Labels: bug

#53 [DOCS] Document client functions and user {major}.{minor} version in links
  api_generator/Cargo.toml
  api_generator/src/api_generator/code_gen/request/request_builder.rs
  api_generator/src/api_generator/mod.rs
  elasticsearch/src/generated/namespace_clients/cat.rs
  elasticsearch/src/generated/namespace_clients/ccr.rs
  elasticsearch/src/generated/namespace_clients/cluster.rs
  elasticsearch/src/generated/namespace_clients/enrich.rs
  elasticsearch/src/generated/namespace_clients/graph.rs
  elasticsearch/src/generated/namespace_clients/ilm.rs
  elasticsearch/src/generated/namespace_clients/indices.rs
  elasticsearch/src/generated/namespace_clients/ingest.rs
  elasticsearch/src/generated/namespace_clients/license.rs
  elasticsearch/src/generated/namespace_clients/migration.rs
  elasticsearch/src/generated/namespace_clients/ml.rs
  elasticsearch/src/generated/namespace_clients/nodes.rs
  elasticsearch/src/generated/namespace_clients/security.rs
  elasticsearch/src/generated/namespace_clients/slm.rs
  elasticsearch/src/generated/namespace_clients/snapshot.rs
  elasticsearch/src/generated/namespace_clients/sql.rs
  elasticsearch/src/generated/namespace_clients/ssl.rs
  elasticsearch/src/generated/namespace_clients/tasks.rs
  elasticsearch/src/generated/namespace_clients/watcher.rs
  elasticsearch/src/generated/namespace_clients/xpack.rs
  elasticsearch/src/generated/root.rs
  elasticsearch/src/http/headers.rs
  elasticsearch/src/http/mod.rs
  elasticsearch/src/http/request.rs
  elasticsearch/src/http/response.rs
  elasticsearch/src/http/transport.rs
  elasticsearch/src/lib.rs
Labels: documentation
